import React, { useState, useEffect, useMemo, useRef } from 'react'
import Head from 'next/head'
import Script from 'next/script'
import { useRouter } from 'next/router'
import { supabase } from '../supabase'
import dynamic from 'next/dynamic'

// Стили CSS объявлены в самом верху файла в виде массива строк, чтобы избежать любых проблем со сборщиками и бэктиками
const cssStyles = [
  ':root {',
  '  --primary: #00A4A6;',
  '  --primary-hover: #00898B;',
  '  --dark-slate: #1E293B;',
  '  --text-main: #334155;',
  '  --text-muted: #64748B;',
  '  --border-soft: #CBD5E1;',
  '  --bg-light: #F1F5F9;',
  '  --shadow-premium: 0 10px 30px rgba(0, 164, 166, 0.06), 0 1px 3px rgba(0, 0, 0, 0.02);',
  '  --shadow-dropdown: 0 12px 32px rgba(15, 23, 42, 0.18);',
  '  --primary-light: rgba(0, 164, 166, 0.06);',
  '  --radius-bubble: 36px;',
  '}',
  '',
  '.tilda-catalog-wrapper, .tilda-catalog-wrapper * {',
  '  font-family: "Mulish", sans-serif !important;',
  '  box-sizing: border-box !important;',
  '}',
  '',
  '.dropdown-mobile-header, .dropdown-mobile-footer {',
  '  display: none !important;',
  '}',
  '.mobile-filter-floating-btn {',
  '  display: none !important;',
  '}',
  '',
  '.input-icon-svg {',
  '  width: 18px !important;',
  '  height: 18px !important;',
  '  flex-shrink: 0 !important;',
  '  transition: stroke .2s, fill .2s !important;',
  '  display: inline-block !important;',
  '}',
  '.input-icon-svg.icon-stroke {',
  '  fill: none !important;',
  '  stroke: var(--text-muted) !important;',
  '  stroke-width: 2 !important;',
  '}',
  '.input-icon-svg.icon-fill {',
  '  fill: var(--text-muted) !important;',
  '}',
  '.search-input-field:hover .input-icon-svg.icon-stroke,',
  '.search-input-field.active-field .input-icon-svg.icon-stroke {',
  '  stroke: var(--primary) !important;',
  '}',
  '.search-input-field:hover .input-icon-svg.icon-fill,',
  '.search-input-field.active-field .input-icon-svg.icon-fill {',
  '  fill: var(--primary) !important;',
  '}',
  '',
  '.search-input-field {',
  '  position: relative !important;',
  '}',
  '',
  '/* ВЫПАДАЮЩИЕ МЕНЮ */',
  '.custom-dropdown {',
  '  position: absolute !important;',
  '  background-color: #ffffff !important;',
  '  border-radius: 16px !important;',
  '  box-shadow: var(--shadow-dropdown) !important;',
  '  border: 1.5px solid var(--border-soft) !important;',
  '  padding: 0 !important;',
  '  z-index: 99999 !important;',
  '  display: none !important;',
  '  overflow: hidden !important;',
  '  top: 100% !important;',
  '  left: 0 !important;',
  '  width: 100% !important;',
  '  margin-top: 4px !important;',
  '}',
  '',
  '.custom-dropdown.active-desktop {',
  '  display: block !important;',
  '}',
  '',
  '/* Gray Backdrop Overlay */',
  '.modal-backdrop-overlay {',
  '  display: none !important;',
  '  position: fixed !important;',
  '  top: 0 !important;',
  '  left: 0 !important;',
  '  width: 100% !important;',
  '  height: 100% !important;',
  '  background: rgba(15, 23, 42, .6) !important;',
  '  z-index: 99999998 !important;',
  '  opacity: 0 !important;',
  '  transition: opacity .3s ease-in-out !important;',
  '  pointer-events: none !important;',
  '}',
  '.modal-backdrop-overlay.show {',
  '  display: block !important;',
  '  opacity: 1 !important;',
  '  pointer-events: auto !important;',
  '}',
  '',
  '/* СТИЛИ ДВОЙНОГО ПОЛЗУНКА */',
  '.dual-range-slider-container {',
  '  position: relative !important;',
  '  width: calc(100% - 20px) !important;',
  '  height: 4px !important;',
  '  background-color: var(--border-soft) !important;',
  '  margin: 15px 10px 25px 10px !important;',
  '  border-radius: 2px !important;',
  '}',
  '.dual-range-track {',
  '  position: absolute !important;',
  '  height: 100% !important;',
  '  background: linear-gradient(90deg, #B2EBF2 0%, #00A4A6 100%) !important;',
  '  border-radius: 2px !important;',
  '  z-index: 1 !important;',
  '}',
  '.dual-range-slider-container input[type="range"] {',
  '  position: absolute !important;',
  '  width: 100% !important;',
  '  height: 4px !important;',
  '  background: transparent !important;',
  '  appearance: none !important;',
  '  -webkit-appearance: none !important;',
  '  pointer-events: none !important;',
  '  outline: none !important;',
  '  margin: 0 !important;',
  '  top: 0 !important;',
  '  left: 0 !important;',
  '  z-index: 2 !important;',
  '}',
  '.dual-range-slider-container input[type="range"]::-webkit-slider-thumb {',
  '  appearance: none !important;',
  '  -webkit-appearance: none !important;',
  '  pointer-events: auto !important;',
  '  width: 18px !important;',
  '  height: 18px !important;',
  '  border-radius: 50% !important;',
  '  border: 2.5px solid var(--primary) !important;',
  '  background-color: #fff !important;',
  '  box-shadow: 0 2px 5px rgba(0,0,0,.1) !important;',
  '  cursor: pointer !important;',
  '  transition: transform .15s, box-shadow .15s !important;',
  '  position: relative !important;',
  '  z-index: 3 !important;',
  '}',
  '.dual-range-slider-container input[type="range"]::-webkit-slider-thumb:hover {',
  '  transform: scale(1.1) !important;',
  '  box-shadow: 0 0 0 6px rgba(0,164,166,.12) !important;',
  '}',
  '.dual-range-slider-container input[type="range"]::-moz-range-thumb {',
  '  pointer-events: auto !important;',
  '  width: 18px !important;',
  '  height: 18px !important;',
  '  border-radius: 50% !important;',
  '  border: 2.5px solid var(--primary) !important;',
  '  background-color: #fff !important;',
  '  box-shadow: 0 2px 5px rgba(0,0,0,.1) !important;',
  '  cursor: pointer !important;',
  '  position: relative !important;',
  '  z-index: 3 !important;',
  '}',
  '',
  '/* КНОПКА СКРЫТИЯ САЙДБАРА НА ДЕСКТОПЕ */',
  '#sidebar-toggle-btn {',
  '  position: fixed !important;',
  '  top: 50% !important;',
  '  left: 0 !important;',
  '  transform: translateY(-50%) !important;',
  '  width: 24px !important;',
  '  height: 60px !important;',
  '  background: var(--primary) !important;',
  '  color: #fff !important;',
  '  border-radius: 0 8px 8px 0 !important;',
  '  display: flex !important;',
  '  align-items: center !important;',
  '  justify-content: center !important;',
  '  cursor: pointer !important;',
  '  z-index: 99999999 !important;',
  '  box-shadow: 2px 0 10px rgba(0,0,0,.1) !important;',
  '  font-size: 14px !important;',
  '  font-weight: 700 !important;',
  '  user-select: none !important;',
  '  transition: background .2s ease !important;',
  '}',
  '#sidebar-toggle-btn:hover {',
  '  background: var(--primary-hover) !important;',
  '}',
  '',
  '/* ЖЕСТКИЙ ЦИАН ГРИД 4Х С ТОЧНЫМИ РАЗМЕРАМИ */',
  '.grid-layout {',
  '  display: grid !important;',
  '  grid-template-columns: repeat(auto-fill, minmax(227.5px, 1fr)) !important;',
  '  gap: 20px !important;',
  '  width: 100% !important;',
  '}',
  '',
  '.cian-card {',
  '  background: #ffffff !important;',
  '  border-radius: 16px !important;',
  '  border: 1px solid rgba(226, 232, 240, 0.6) !important;',
  '  overflow: hidden !important;',
  '  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.02) !important;',
  '  display: flex !important;',
  '  flex-direction: column !important;',
  '  transition: transform .25s ease, box-shadow .25s ease !important;',
  '  position: relative !important;',
  '  cursor: pointer !important;',
  '  text-decoration: none !important;',
  '}',
  '@media (min-width: 1025px) {',
  '  .grid-layout .cian-card {',
  '    width: 227.5px !important;',
  '    height: 302.26px !important;',
  '  }',
  '}',
  '.cian-card:hover {',
  '  transform: translateY(-5px) !important;',
  '  box-shadow: 0 16px 36px rgba(15, 23, 42, 0.06) !important;',
  '}',
  '',
  '.cian-img-container {',
  '  position: relative !important;',
  '  overflow: hidden !important;',
  '  border-radius: 12px !important;',
  '  width: 100% !important;',
  '}',
  '@media (min-width: 1025px) {',
  '  .cian-img-container {',
  '    height: 184.93px !important;',
  '  }',
  '}',
  '@media (max-width: 1024px) {',
  '  .cian-img-container {',
  '    aspect-ratio: 1.22 !important;',
  '  }',
  '}',
  '',
  '.cian-img {',
  '  position: absolute !important;',
  '  top: 0 !important;',
  '  left: 0 !important;',
  '  width: 100% !important;',
  '  height: 100% !important;',
  '  object-fit: cover !important;',
  '  transition: transform 0.4s ease !important;',
  '}',
  '.cian-card:hover .cian-img {',
  '  transform: scale(1.04) !important;',
  '}',
  '',
  '/* Кнопка сердечка на карточках */',
  '.card-fav-btn {',
  '  position: absolute !important;',
  '  top: 12px !important;',
  '  right: 12px !important;',
  '  width: 36px !important;',
  '  height: 36px !important;',
  '  border-radius: 50% !important;',
  '  background: rgba(15, 23, 42, 0.35) !important;',
  '  backdrop-filter: blur(4px) !important;',
  '  border: none !important;',
  '  color: #ffffff !important;',
  '  display: flex !important;',
  '  align-items: center !important;',
  '  justify-content: center !important;',
  '  cursor: pointer !important;',
  '  z-index: 10 !important;',
  '  transition: all 0.2s ease !important;',
  '  padding: 0 !important;',
  '}',
  '.card-fav-btn:hover {',
  '  background: rgba(15, 23, 42, 0.55) !important;',
  '  transform: scale(1.08) !important;',
  '}',
  '.card-fav-btn.liked {',
  '  color: #ff3b30 !important;',
  '  background: #ffffff !important;',
  '  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1) !important;',
  '}',
  '',
  '/* Скрытые стрелки на картинке (проявляются белым при наведении) */',
  '.slider-arrow {',
  '  position: absolute !important;',
  '  top: 50% !important;',
  '  transform: translateY(-50%) !important;',
  '  background: rgba(255, 255, 255, 0) !important;',
  '  color: rgba(255, 255, 255, 0) !important;',
  '  border: none !important;',
  '  width: 30px !important;',
  '  height: 30px !important;',
  '  border-radius: 50% !important;',
  '  cursor: pointer !important;',
  '  transition: all 0.2s ease !important;',
  '  z-index: 8 !important;',
  '  display: flex !important;',
  '  align-items: center !important;',
  '  justify-content: center !important;',
  '  font-weight: 900 !important;',
  '  user-select: none !important;',
  '}',
  '.arrow-left { left: 8px !important; }',
  '.arrow-right { right: 8px !important; }',
  '.cian-card:hover .slider-arrow {',
  '  background: rgba(255, 255, 255, 0.8) !important;',
  '  color: var(--dark-slate) !important;',
  '}',
  '.cian-card:hover .slider-arrow:hover {',
  '  background: rgba(255, 255, 255, 1) !important;',
  '}',
  '',
  '.card-badge {',
  '  position: absolute !important;',
  '  top: 12px !important;',
  '  left: 12px !important;',
  '  color: #ffffff !important;',
  '  font-size: 10px !important;',
  '  font-weight: 800 !important;',
  '  text-transform: uppercase !important;',
  '  padding: 5px 12px !important;',
  '  border-radius: 20px !important;',
  '  z-index: 5 !important;',
  '  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1) !important;',
  '  letter-spacing: 0.5px !important;',
  '}',
  '.status-lansman { background-color: #ff9800 !important; }',
  '.status-other { background-color: var(--primary) !important; }',
  '',
  '/* Текстовая область */',
  '.cian-info {',
  '  padding: 12px 6px 14px 6px !important;',
  '  display: flex !important;',
  '  flex-direction: column !important;',
  '  gap: 4px !important;',
  '  min-height: 117.33px !important;',
  '}',
  '.cian-price {',
  '  font-size: 21px !important;',
  '  font-weight: 900 !important;',
  '  color: var(--text-main) !important;',
  '  line-height: 1.2 !important;',
  '}',
  '.cian-specs {',
  '  font-size: 14.5px !important;',
  '  font-weight: 700 !important;',
  '  color: #334155 !important;',
  '  line-height: 1.4 !important;',
  '}',
  '.cian-location {',
  '  font-size: 13px !important;',
  '  font-weight: 600 !important;',
  '  color: #475569 !important;',
  '  display: inline-flex !important;',
  '  align-items: center !important;',
  '  gap: 6px !important;',
  '  line-height: 1.4 !important;',
  '}',
  '.cian-geo-dot {',
  '  width: 8px !important;',
  '  height: 8px !important;',
  '  border-radius: 50% !important;',
  '  flex-shrink: 0 !important;',
  '}',
  '.cian-geo-dot.cyan { background-color: var(--primary) !important; }',
  '.cian-address {',
  '  font-size: 12px !important;',
  '  font-weight: 500 !important;',
  '  color: var(--text-muted) !important;',
  '  white-space: nowrap !important;',
  '  overflow: hidden !important;',
  '  text-overflow: ellipsis !important;',
  '  line-height: 1.4 !important;',
  '}',
  '',
  '/* ВЫДВИЖНОЙ РАЗДЕЛ (ЛИЧНЫЙ КАБИНЕТ) */',
  '.cabinet-drawer {',
  '  position: fixed !important;',
  '  top: 0 !important;',
  '  right: -420px !important;',
  '  width: 400px !important;',
  '  height: 100vh !important;',
  '  background: #ffffff !important;',
  '  box-shadow: -10px 0 40px rgba(0, 0, 0, 0.15) !important;',
  '  z-index: 10000005 !important;',
  '  transition: right 0.3s cubic-bezier(0.16, 1, 0.3, 1) !important;',
  '  display: flex !important;',
  '  flex-direction: column !important;',
  '}',
  '.cabinet-drawer.open {',
  '  right: 0 !important;',
  '}',
  '.drawer-header {',
  '  padding: 24px !important;',
  '  border-bottom: 1px solid var(--border-soft) !important;',
  '  display: flex !important;',
  '  align-items: center !important;',
  '  justify-content: space-between !important;',
  '}',
  '.drawer-title {',
  '  font-size: 20px !important;',
  '  font-weight: 900 !important;',
  '  color: var(--text-main) !important;',
  '}',
  '.drawer-close {',
  '  background: none !important;',
  '  border: none !important;',
  '  font-size: 28px !important;',
  '  color: var(--text-muted) !important;',
  '  cursor: pointer !important;',
  '}',
  '.drawer-content {',
  '  flex: 1 !important;',
  '  overflow-y: auto !important;',
  '  padding: 24px !important;',
  '}',
  '.fav-list {',
  '  display: flex !important;',
  '  flex-direction: column !important;',
  '  gap: 16px !important;',
  '}',
  '.drawer-empty-placeholder {',
  '  text-align: center !important;',
  '  padding: 40px 0 !important;',
  '  color: var(--text-muted) !important;',
  '}',
  '',
  '/* МОДАЛЬНОЕ ОКНО ПОДАЧИ ОБЪЯВЛЕНИЯ */',
  '.modal-overlay {',
  '  position: fixed !important;',
  '  top: 0 !important;',
  '  left: 0 !important;',
  '  width: 100vw !important;',
  '  height: 100vh !important;',
  '  background: rgba(15, 23, 42, 0.6) !important;',
  '  backdrop-filter: blur(4px) !important;',
  '  z-index: 10000010 !important;',
  '  display: none !important;',
  '  align-items: center !important;',
  '  justify-content: center !important;',
  '}',
  '.modal-overlay.open {',
  '  display: flex !important;',
  '}',
  '.modal-card-box {',
  '  background: #ffffff !important;',
  '  width: 450px !important;',
  '  max-width: 90% !important;',
  '  border-radius: 20px !important;',
  '  padding: 32px !important;',
  '  box-shadow: 0 20px 50px rgba(0,0,0,0.15) !important;',
  '  position: relative !important;',
  '  text-align: center !important;',
  '}',
  '.modal-close-btn {',
  '  position: absolute !important;',
  '  top: 20px !important;',
  '  right: 20px !important;',
  '  background: none !important;',
  '  border: none !important;',
  '  font-size: 24px !important;',
  '  color: var(--text-muted) !important;',
  '  cursor: pointer !important;',
  '}',
  '.phone-highlight-block {',
  '  font-size: 20px !important;',
  '  font-weight: 800 !important;',
  '  color: var(--primary) !important;',
  '  background: rgba(0, 164, 166, 0.05) !important;',
  '  padding: 12px !important;',
  '  border-radius: 12px !important;',
  '  display: inline-block !important;',
  '  margin-bottom: 20px !important;',
  '}',
  '.modal-green-btn {',
  '  display: block !important;',
  '  width: 100% !important;',
  '  background: #25D366 !important;',
  '  color: #ffffff !important;',
  '  text-decoration: none !important;',
  '  padding: 14px !important;',
  '  border-radius: 12px !important;',
  '  font-weight: 800 !important;',
  '  font-size: 15px !important;',
  '}',
  '',
  '/* ПОЛНОЭКРАННЫЙ LIGHTBOX СЧЕТЧИК */',
  '.lightbox-counter {',
  '  position: absolute !important;',
  '  bottom: 40px !important;',
  '  left: 50% !important;',
  '  transform: translateX(-50%) !important;',
  '  color: #fff !important;',
  '  font-size: 15px !important;',
  '  font-weight: 800 !important;',
  '  z-index: 101 !important;',
  '  background-color: rgba(30, 41, 59, 0.85) !important;',
  '  padding: 8px 18px !important;',
  '  border-radius: 30px !important;',
  '  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3) !important;',
  '  backdrop-filter: blur(4px) !important;',
  '  user-select: none !important;',
  '}',
  '',
  '@media (max-width: 1024px) {',
  '  .hero-search-title { display: none !important; }',
  '  .mobile-only-title {',
  '    display: block !important;',
  '    font-size: 20px !important;',
  '    font-weight: 800 !important;',
  '    color: #ffffff !important;',
  '    text-align: center !important;',
  '    margin: 0 auto 20px auto !important;',
  '    line-height: 1.3 !important;',
  '  }',
  '  .hero-search-container {',
  '    padding: 110px 20px 24px 20px !important;',
  '    background: linear-gradient(180deg, #00A4A6 0%, #062228 100%) !important;',
  '  }',
  '  .search-tabs-header {',
  '    justify-content: center !important;',
  '    gap: 8px !important;',
  '    margin-bottom: 16px !important;',
  '    border-bottom: none !important;',
  '    padding-bottom: 0 !important;',
  '  }',
  '  .city-tab-item {',
  '    padding: 8px 16px !important;',
  '    border-radius: 20px !important;',
  '    background-color: rgba(255,255,255,0.12) !important;',
  '    color: #fff !important;',
  '    font-size: 14px !important;',
  '    font-weight: 800 !important;',
  '    margin-bottom: 0 !important;',
  '  }',
  '  .city-tab-item.active {',
  '    background-color: #fff !important;',
  '    color: var(--primary) !important;',
  '  }',
  '  .city-tab-item.active::after { display: none !important; }',
  '  .city-tab-item.disabled { display: none !important; }',
  '',
  '  .search-panel-card {',
  '    border: none !important;',
  '    box-shadow: none !important;',
  '    background: transparent !important;',
  '    padding: 0 !important;',
  '  }',
  '  .search-inputs-row-wrapper {',
  '    flex-direction: column !important;',
  '  }',
  '  .search-inputs-row {',
  '    display: grid !important;',
  '    grid-template-columns: repeat(2, 1fr) !important;',
  '    grid-template-rows: auto auto !important;',
  '    gap: 0 !important;',
  '    border: 1px solid var(--border-soft) !important;',
  '    border-radius: 16px !important;',
  '    overflow: visible !important;',
  '    background-color: #fff !important;',
  '    width: 368px !important;',
  '    max-width: 100% !important;',
  '    box-sizing: border-box !important;',
  '    margin: 0 auto !important;',
  '  }',
  '  .search-input-field {',
  '    background-color: #fff !important;',
  '    border: none !important;',
  '    border-radius: 0 !important;',
  '    height: 44px !important;',
  '    padding: 0 12px !important;',
  '    width: 100% !important;',
  '    box-shadow: none !important;',
  '  }',
  '  .field-trigger-location {',
  '    grid-column: span 2 !important;',
  '    border-bottom: 1px solid var(--border-soft) !important;',
  '  }',
  '  .field-trigger-room {',
  '    grid-column: span 1 !important;',
  '    border-right: 1px solid var(--border-soft) !important;',
  '  }',
  '  .field-trigger-durum {',
  '    grid-column: span 1 !important;',
  '  }',
  '',
  '  .input-double-label {',
  '    position: relative !important;',
  '    height: 100% !important;',
  '  }',
  '  .input-double-label .sub-label {',
  '    position: absolute !important;',
  '    top: 50% !important;',
  '    transform: translateY(-50%) !important;',
  '    font-size: 15px !important;',
  '    text-transform: none !important;',
  '    font-weight: 600 !important;',
  '    transition: opacity 0.25s ease !important;',
  '  }',
  '  .input-double-label .main-label {',
  '    position: absolute !important;',
  '    top: 50% !important;',
  '    transform: translateY(-50%) !important;',
  '    font-size: 15px !important;',
  '    font-weight: 700 !important;',
  '    opacity: 0 !important;',
  '    transition: opacity 0.25s ease !important;',
  '    width: 100% !important;',
  '    white-space: nowrap !important;',
  '    overflow: hidden !important;',
  '    text-overflow: ellipsis !important;',
  '  }',
  '  .search-input-field.has-value .input-double-label .sub-label {',
  '    opacity: 0 !important;',
  '  }',
  '  .search-input-field.has-value .input-double-label .main-label {',
  '    opacity: 1 !important;',
  '  }',
  '',
  '  .search-submit-btn {',
  '    width: 368px !important;',
  '    max-width: 100% !important;',
  '    height: 48px !important;',
  '    margin-top: 12px !important;',
  '    border-radius: 12px !important;',
  '  }',
  '',
  '  /* МОБИЛЬНЫЕ ШТОРКИ ВЫПАДАЮЩИХ СПИСКОВ */',
  '  .custom-dropdown {',
  '    position: fixed !important;',
  '    bottom: 0 !important;',
  '    top: 0 !important;',
  '    left: 0 !important;',
  '    right: 0 !important;',
  '    width: 100% !important;',
  '    max-width: 100% !important;',
  '    height: 100vh !important;',
  '    border-radius: 0 !important;',
  '    box-shadow: 0 -10px 40px rgba(15,23,42,0.15) !important;',
  '    z-index: 100000005 !important;',
  '    display: none !important;',
  '    flex-direction: column !important;',
  '    background-color: #fff !important;',
  '    border: none !important;',
  '    transform: translateY(100%);',
  '    transition: transform .3s cubic-bezier(.16,1,.3,1) !important;',
  '  }',
  '',
  '  .custom-dropdown.active-mobile-modal {',
  '    display: flex !important;',
  '    transform: translateY(0) !important;',
  '    z-index: 100000005 !important;',
  '  }',
  '',
  '  .custom-dropdown::before {',
  '    content: \'\' !important;',
  '    display: block !important;',
  '    width: 40px !important;',
  '    height: 4px !important;',
  '    background-color: #cbd5e1 !important;',
  '    border-radius: 2px !important;',
  '    margin: 12px auto 8px auto !important;',
  '    flex-shrink: 0 !important;',
  '  }',
  '',
  '  .dropdown-mobile-header {',
  '    display: flex !important;',
  '    justify-content: space-between !important;',
  '    align-items: center !important;',
  '    padding: 12px 20px !important;',
  '    border-bottom: 1px solid var(--border-soft) !important;',
  '    flex-shrink: 0 !important;',
  '  }',
  '  .dropdown-mobile-title {',
  '    font-size: 16px !important;',
  '    font-weight: 900 !important;',
  '    color: #3F536C !important;',
  '  }',
  '  .dropdown-mobile-close {',
  '    font-size: 24px !important;',
  '    color: var(--text-muted) !important;',
  '    cursor: pointer !important;',
  '  }',
  '',
  '  /* МОБИЛЬНЫЙ САЙДБАР */',
  '  .luxe-sidebar {',
  '    position: fixed !important;',
  '    top: 0 !important;',
  '    left: -320px !important;',
  '    width: 300px !important;',
  '    height: 100% !important;',
  '    border-radius: 0 24px 24px 0 !important;',
  '    z-index: 9999999 !important;',
  '    box-shadow: 10px 0 30px rgba(15, 23, 42, .15) !important;',
  '    display: flex !important;',
  '    flex-direction: column !important;',
  '    overflow: hidden !important;',
  '    padding: 0 !important;',
  '    transition: left .3s ease !important;',
  '    background: #fff !important;',
  '  }',
  '  .luxe-sidebar.sidebar-mobile-show {',
  '    left: 0 !important;',
  '  }',
  '  ',
  '  /* Мобильный футер */',
  '  .luxe-sidebar-mobile-footer {',
  '    display: flex !important;',
  '    position: absolute !important;',
  '    bottom: 0 !important;',
  '    left: 0 !important;',
  '    width: 100% !important;',
  '    background-color: #fff !important;',
  '    border-top: 1px solid var(--border-soft) !important;',
  '    padding: 12px 20px !important;',
  '    box-sizing: border-box !important;',
  '    z-index: 110 !important;',
  '    gap: 10px !important;',
  '  }',
  '  .luxe-sidebar-mobile-footer .c-button {',
  '    flex: 1 !important;',
  '    height: 42px !important;',
  '    border-radius: 8px !important;',
  '    display: inline-flex !important;',
  '    align-items: center !important;',
  '    justify-content: center !important;',
  '    font-size: 13px !important;',
  '    font-weight: 800 !important;',
  '    text-decoration: none !important;',
  '    box-sizing: border-box !important;',
  '    border: none !important;',
  '  }',
  '  .luxe-sidebar-mobile-footer .c-button--primary {',
  '    background-color: var(--primary) !important;',
  '    color: #fff !important;',
  '  }',
  '  .luxe-sidebar-mobile-footer .c-button--transparent {',
  '    background-color: transparent !important;',
  '    color: var(--text-muted) !important;',
  '    border: 1px solid var(--border-soft) !important;',
  '  }',
  '',
  '  .mobile-filter-floating-btn {',
  '    display: flex !important;',
  '    position: fixed !important;',
  '    bottom: 20px !important;',
  '    left: 50% !important;',
  '    transform: translateX(-50%) !important;',
  '    background-color: var(--primary) !important;',
  '    color: #ffffff !important;',
  '    font-weight: 800 !important;',
  '    padding: 14px 28px !important;',
  '    border-radius: 30px !important;',
  '    box-shadow: 0 10px 25px rgba(0, 164, 166, 0.3) !important;',
  '    z-index: 99999 !important;',
  '    text-transform: uppercase !important;',
  '    font-size: 13px !important;',
  '    letter-spacing: 0.5px !important;',
  '    align-items: center !important;',
  '    gap: 8px !important;',
  '    cursor: pointer !important;',
  '    border: none !important;',
  '    white-space: nowrap !important;',
  '  }',
  '  .sidebar-mobile-close-btn {',
  '    display: flex !important;',
  '    width: 36px !important;',
  '    height: 36px !important;',
  '    background-color: rgba(207,212,218,0.3) !important;',
  '    border-radius: 50% !important;',
  '    align-items: center !important;',
  '    justify-content: center !important;',
  '    position: absolute !important;',
  '    top: 15px !important;',
  '    right: 20px !important;',
  '    z-index: 101 !important;',
  '    cursor: pointer !important;',
  '    color: #3F536C !important;',
  '    font-size: 22px !important;',
  '  }',
  '  .luxe-sidebar-scrollable-body {',
  '    flex: 1 !important;',
  '    overflow-y: auto !important;',
  '    padding: 24px 20px 80px 20px !important;',
  '    width: 100% !important;',
  '  }',
  '  #catalog-content-wrapper {',
  '    margin-left: 0 !important;',
  '  }',
  '  ',
  '  .v1-grid {',
  '    grid-template-columns: 1fr !important;',
  '    gap: 20px !important;',
  '  }',
  '  .v1-card {',
  '    padding: 30px 20px !important;',
  '    border-radius: 24px !important;',
  '  }',
  '  .v1-footer-panel {',
  '    flex-direction: column !important;',
  '    padding: 24px 20px !important;',
  '  }',
  '',
  '  .grid-layout, .list-layout {',
  '    display: flex !important;',
  '    flex-direction: column !important;',
  '    gap: 24px !important;',
  '    width: 100% !important;',
  '  }',
  '  .list-layout .custom-card {',
  '    flex-direction: column !important;',
  '  }',
  '  .list-layout .custom-card .img-container {',
  '    width: 100% !important;',
  '    height: 200px !important;',
  '  }',
  '}'
].join('\n');

// Динамический импорт компонентов без SSR
const Header = dynamic(() => import('../components/Header'), { ssr: false })
const Footer = dynamic(() => import('../components/Footer'), { ssr: false })
const PropertyCard = dynamic(() => import('../components/PropertyCard'), { ssr: false })

export async function getServerSideProps() {
  try {
    const { data: properties, error } = await supabase
      .from('properties')
      .select('*')

    const sortedProperties = properties ? [...properties].sort((a, b) => {
      const idA = parseInt(a.id || a["Номер"]) || 0;
      const idB = parseInt(b.id || b["Номер"]) || 0;
      return idB - idA;
    }) : [];

    if (error) throw error

    return {
      props: {
        properties: sortedProperties,
        initialError: null,
      },
    }
  } catch (err) {
    console.error('❌ Supabase Veri Cekme Hatasi:', err);
    const errMsg = err && typeof err === 'object' ? err.message || JSON.stringify(err) : String(err);
    return {
      props: {
        properties: [],
        initialError: errMsg || 'Supabase connection failed',
      },
    }
  }
}
